FROM debian:jessie
RUN apt-get update && apt-get install -y --no-install-recommends zip xsltproc xmlto unzip python-simplejson make git rsync dpkg-dev debhelper dh-systemd erlang-dev erlang-nox erlang-src fakeroot build-essential
