FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

# Choosing erlang version explicity, so we will not have a lot of GUI libraries
{% set erlang_deps = 'erlang-nox erlang-base-hipe' %}

# Runtime deps of rabbitmq
{% set rabbit_run_deps = 'socat logrotate' %}

# Manually managing dependencies, as we don't yet have APT repos with proper versions
# of rabbitmq and autocluster.
RUN apt-get install -t jessie-backports -y --no-install-recommends \
  {{ erlang_deps }} {{ rabbit_run_deps }} \
  && apt-get clean

# We need at least 3.6.6, as it'll contain https://github.com/rabbitmq/rabbitmq-server/pull/892
RUN curl -Lo /tmp/rabbitmq-server.deb https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_6_rc2/rabbitmq-server_3.6.5.907-1_all.deb \
  && dpkg -i /tmp/rabbitmq-server.deb \
  && rm -rf /tmp/rabbitmq-server.deb /var/lib/rabbitmq/*

# `cp` is needed until https://github.com/rabbitmq/rabbitmq-server/pull/1016 is merged
RUN curl -Lo /tmp/rabbitmq-autocluster.deb https://github.com/Mirantis/rabbitmq-autocluster/releases/download/0.6.1.950/rabbitmq-autocluster_0.6.1.950-1_all.deb \
  && dpkg -i /tmp/rabbitmq-autocluster.deb \
  && cp -v /usr/lib/rabbitmq/plugins/*.ez /usr/lib/rabbitmq/lib/rabbitmq_server-*/plugins/

COPY rabbitmq_sudoers /etc/sudoers.d/rabbitmq_sudoers

RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/rabbitmq_sudoers \
    && usermod -a -G microservices rabbitmq \
    && chown -R rabbitmq: /var/lib/rabbitmq /etc/rabbitmq

USER rabbitmq
